# Generated by Django 4.2.11 on 2025-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_sitecontent_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'IN Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='published', max_length=10),
        ),
    ]
