# Generated by Django 4.2.11 on 2025-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_order_tracking_id_order_tracking_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('in_review', 'IN Review'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='published', max_length=10),
        ),
    ]
