# Generated by Django 4.2.11 on 2025-07-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('in_review', 'IN Review')], default='published', max_length=10),
        ),
    ]
