# Generated by Django 4.2.11 on 2025-07-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_wishlist_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'IN Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='published', max_length=10),
        ),
    ]
