# Generated by Django 4.2.11 on 2025-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('in_review', 'IN Review'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='published', max_length=10),
        ),
    ]
