# Generated by Django 4.2.11 on 2025-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the brand for admin and alt text.', max_length=100)),
                ('image', models.ImageField(help_text="Upload the brand's logo.", upload_to='brands/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active brands will be displayed on the website.')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'IN Review'), ('rejected', 'Rejected')], default='published', max_length=10),
        ),
    ]
